local languages
if vim.fn.has "unix" == 1 then
  languages = {
    "angular",
    "arduino",
    "awk",
    "bash",
    "c",
    "c_sharp",
    "cmake",
    -- "comment",
    "commonlisp",
    "cpp",
    "css",
    "csv",
    "cuda",
    "d",
    "dart",
    "diff",
    "dockerfile",
    "dot",
    "ebnf",
    "elixir",
    "embedded_template",
    "erlang",
    "fennel",
    "git_config",
    "git_rebase",
    "gitattributes",
    "gitcommit",
    "gitignore",
    "glsl",
    "go",
    "gomod",
    "gosum",
    "graphql",
    "groovy",
    "hack",
    "haskell",
    "haskell_persistent",
    "hcl",
    "hlsl",
    "hocon",
    "html",
    "http",
    "java",
    "javascript",
    "jq",
    "jsdoc",
    "json",
    "json5",
    "jsonc",
    "jsonnet",
    "kconfig",
    "latex",
    "lua",
    "luadoc",
    "make",
    "markdown",
    "markdown_inline",
    "matlab",
    "mermaid",
    "meson",
    "ninja",
    "nix",
    "objdump",
    "ocaml",
    "ocaml_interface",
    "pascal",
    "passwd",
    "pem",
    "perl",
    "php",
    "php_only",
    "phpdoc",
    "promql",
    "properties",
    "pug",
    "pymanifest",
    "python",
    "query",
    "rasi",
    "regex",
    "requirements",
    "ruby",
    "rust",
    "scheme",
    "scss",
    "sql",
    "ssh_config",
    "strace",
    "svelte",
    "toml",
    "tsx",
    "typescript",
    "v",
    "vala",
    "verilog",
    "vim",
    "vimdoc",
    "vue",
    "xml",
    "yaml",
    "zig",
  }
  languages = nil
elseif vim.fn.has "win64" == 1 then
  languages = {
    "java",
    "kotlin",
    "javascript",
    "lua",
    "python",
  }
end

return {
  {
    "nvim-treesitter/nvim-treesitter-context",
    opts = {
      enable = true,
      mode = "cursor",
    },
  },
  {
    -- "~/projects/neovim/nvim-treesitter",
    "nvim-treesitter/nvim-treesitter",
    -- commit = "668de0951a36ef17016074f1120b6aacbe6c4515",
    dependencies = {
      "nvim-treesitter/nvim-treesitter-textobjects",
      "windwp/nvim-ts-autotag",
      "nvim-treesitter/nvim-treesitter-context",
    },
    branch = "master",
    lazy = false,
    build = ":TSUpdate",
    config = function()
      require "nvim-treesitter.configs".setup {
        ensure_installed = languages,

        highlight = {
          enable = true,
        },
        incremental_selection = {
          enable = true,
          keymaps = {
            init_selection = "<Leader>)",
            node_incremental = ")",
            node_decremental = "(",
          },
        },
        blockmark = {
          enable = true,
        },
        -- textobjects = {
        --   select = {
        --     enable = true,
        --     lookahead = true,
        --     lookbehind = true,
        --     keymaps = {
        --       ["aa"] = "@parameter.outer",
        --       ["ia"] = "@parameter.inner",
        --       ["ib"] = "@block.inner",
        --       ["ab"] = "@block.outer",
        --     },
        --   },
        --   move = {
        --     enable = true,
        --   },
        -- },
      }
    end,
    init = function()
      -- Disable semantic highlight of `#if`, `#ifdef` etc
      vim.api.nvim_set_hl(0, "@lsp.type.comment", {})
    end,
  },
}
