version: "1"

bat_common: &bat_common
  level_icons: ["", "", "", "", ""]
  state_icons:
    charging: ''
  urgent_level: 10

pulse_icons: &pulse_icons
  devices:
    Speakers: "墳"
    Headphones: ""
    Headset: ""
    Microphone: ""
    Internal Microphone: ""
    Headset Microphone: ""
  sink_muted: ""
  source_muted: ""

separator_width: 16

theme:
  saturation: 80
  value: 90

blocks:

  # - name: shell
  #   command: |
  #     jwt=""
  #     url="https://mw-api.vodafone.ua/prepaybalance/tmf-api/prepayBalanceManagement/v4/bucket"
  #     curl -sf --compressed "${url}" \
  #       -A 'Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0' \
  #       -H 'X-DEVICE-SOURCE: UNIX OS' \
  #       -H 'Profile: COUNTERS-DATA' \
  #       -H "Authorization: Bearer ${jwt}" | jq -r \
  #       ' .[]
  #       | select(.bucketType == "VFNewProMonth")
  #       | "\(.remainingValue.amount)/\(.maximumAmount) \(.remainingValue.units)"'
  #   interval: 1m

  # - name: shell
  #   command: |
  #     curl -s "https://war-api.ukrzen.in.ua/alerts/api/alerts/active.json" \
  #     | jq -r \
  #     ' (.alerts | map(.location_title | select(test("кірово"; "i")))) as $l
  #     | if $l | length > 0 then
  #         { full_text: ("䀘 " + ($l | join(", "))), urgent: true }
  #       else
  #         ""
  #       end'
  #   json: true
  #   interval: 1m

  - name: shell
    command: ~/.config/sway/bar-scripts/weather.sh
    on_click: |
      [ $BUTTON = Left ] && ~/.config/sway/bar-scripts/weather.sh -o
    interval: 5m

  - name: pulseaudio
    node: sink
    format: "{icon}{volume:3*%}"
    on_click: |
      case $BUTTON in
        Right) ~/.config/sway/bar-scripts/switch_audio_sink.py next;;
        Left) if ! pgrep -x pavucontrol; then pavucontrol -t 3; fi;;
      esac
    icons: *pulse_icons

  - name: pulseaudio
    node: source
    format: "{icon}{volume:3*%}"
    icons: *pulse_icons
    on_click: |
      case $BUTTON in
        Left) if ! pgrep -x pavucontrol; then pavucontrol -t 4; fi;;
      esac

  - name: bluez
    format: " {devices}"
    device_format: "{icon}"
    on_click: |
      case $BUTTON in
        Left) blueman-manager;;
      esac
    icons:
      phone: " "
      audio-card: " "
      audio-headset: " "
      input-keyboard: " "

  - name: networkmanager
    format: "{status_icon}{vpn}{access_point}"
    ap_format: "{strength:3*%}"
    icons:
      vpn: "嬨"
      wifi:
        unavailable: "直"
        connected: "直"
        disconnected: "睊"
        connecting: "直 "
        connected_local: "直"
      ethernet:
        connected: ""
        disconnected: ""
    on_click: if ! pgrep -x nmtui; then foot --app-id foot_floating nmtui; fi

  - name: shell
    command: >
      awk -f ~/.config/sway/bar-scripts/cputemp.awk <(sensors)
    interval: 10s
    json: true

  - <<: *bat_common
    name: battery
    format: " {state_icon}{percentage:3*%}"
    upower_device: keyboard_hid_dco2co26o0co73o0b_battery

  - <<: *bat_common
    name: battery
    format: "{is_charging$}{state_icon}{percentage:3*%}"

  - name: sway_layout
    format: "{flag}"

  # - name: time
  - name: shell
    command: |
      while :; do
        date +'%a %x %X'
        sleep 1
      done
