icons_format = "{icon}"

[theme]
theme = "native"
[theme.overrides]
# idle_bg = "#123456"
# idle_fg = "#abcdef"
good_fg = "#00bb00"
warning_fg = "#ffbb00"
critical_fg = "#dd0000"

[icons]
icons = "material-nf"
[icons.overrides]
bat = ["󰁺", "󰁻", "󰁼", "󰁽", "󰁾", "󰁿", "󰂀", "󰂁", "󰂂", "󰁹"]
bat_charging = "󰂄"
net_tethering = "󱇰"

# [[block]]
# block = "custom"
# command = "/home/kraftwerk28/.config/sway/bar-scripts/weather.py"
# format = "$text"
# persistent = true

[[block]]
block = "cpu"
format = "$icon $utilization $barchart{ $frequency.eng(w:3)|}"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90
interval = 2

[[block]]
block = "memory"
format = " $mem_used.eng(p:Mi,w:3) ($mem_used_percents.eng(w:2))"

[[block]]
block = "sound"
driver = "pulseaudio"
device_kind = "source"
format = "$icon $volume.eng(w:2)"
show_volume_when_muted = true
[[block.click]]
button = "left"
cmd = "pavucontrol --tab=4"

[[block]]
block = "sound"
driver = "pulseaudio"
device_kind = "sink"
format = "$icon $volume.eng(w:2) $output_name"
show_volume_when_muted = true
[[block.click]]
button = "left"
cmd = "pavucontrol --tab=3"
[[block.click]]
button = "right"
cmd = "pavucontrol --tab=3"
[block.mappings]
".*pci-0000_00_1f\\.3\\.analog-stereo.*" = "Builtin"
".*usb-Focusrite_Scarlett_Solo_USB_Y7RH6Z51604365-00.*" = "Focusrite"
"bluez_output.*" = "Bluetooth"

[[block]]
block = "bluetooth"
mac = "00:16:94:38:8F:21"
format = "$icon $name{ $percentage|}"
disconnected_format = "$icon{ $name|}"
[[block.click]]
button = "left"
cmd = "blueman-manager"

[[block]]
block = "net"
device = "wlan0"
format = "^icon_net_wireless{ $ip|}"
inactive_format = ""
missing_format = ""

[[block]]
block = "net"
device = "eth0"
format = "^icon_net_wired{ $ip|}"
inactive_format = ""
missing_format = ""

[[block]]
block = "net"
device = "eth1"
format = "^icon_net_tethering{ $ip|}"
inactive_format = ""
missing_format = ""

[[block]]
block = "custom"
command = "sensors | awk -f $XDG_CONFIG_HOME/sway/bar-scripts/cputemp.awk <(sensors)"
format = "$text"
json = true

[[block]]
block = "battery"
device = "BAT0"
driver = "upower"
format = "$icon $percentage"
full_format = "$icon $percentage"
empty_format = "$icon $percentage"
empty_threshold = 0

[[block]]
block = "keyboard_layout"
driver = "sway"
format = "$layout"
# Flag emojis
[block.mappings]
"English (intl., with AltGr dead keys)" = "🇺🇸"
"Ukrainian (N/A)" = "🇺🇦"

[[block]]
block = "time"
interval = 1
format = "$timestamp.datetime(f:'%a %d.%m %T')"
