[general]
import = [
	"~/.config/alacritty/gruvbox_light.toml"
]

[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 11
offset = { x = 0, y = -0 }

[font.normal]
family = "JetBrains Mono"
style = "Medium"

[cursor]
thickness = 0.2
