local config = {
  highlight = {
    enable = true,
    -- Setting this to true will run `:h syntax` and tree-sitter at the same time.
    -- Set this to `true` if you depend on 'syntax' being enabled (like for indentation).
    -- Using this option may slow down your editor, and you may see some duplicate highlights.
    -- Instead of true it can also be a list of languages
    additional_vim_regex_highlighting = false,
  },
  incremental_selection = {
    enable = true,
    keymaps = {
      init_selection = "<Leader>)",
      node_incremental = ")",
      node_decremental = "(",
    },
  },
  blockmark = {
    enable = true,
  },
  -- textobjects = {
  --   select = {
  --     enable = true,
  --     lookahead = true,
  --     lookbehind = true,
  --     keymaps = {
  --       ["aa"] = "@parameter.outer",
  --       ["ia"] = "@parameter.inner",
  --       ["ib"] = "@block.inner",
  --       ["ab"] = "@block.outer",
  --     },
  --   },
  --   move = {
  --     enable = true,
  --   },
  -- },
}

if vim.fn.has("unix") == 1 then
  config.ensure_installed = {
    "angular",
    "arduino",
    "awk",
    "bash",
    "c",
    "c_sharp",
    "cmake",
    "comment",
    "commonlisp",
    "cpp",
    "css",
    "csv",
    "cuda",
    "d",
    "dart",
    "diff",
    "dockerfile",
    "dot",
    "ebnf",
    "elixir",
    "embedded_template",
    "erlang",
    "fennel",
    "git_config",
    "git_rebase",
    "gitattributes",
    "gitcommit",
    "gitignore",
    "glsl",
    "go",
    "gomod",
    "gosum",
    "graphql",
    "groovy",
    "hack",
    "haskell",
    "haskell_persistent",
    "hcl",
    "hlsl",
    "hocon",
    "html",
    "http",
    "java",
    "javascript",
    "jq",
    "jsdoc",
    "json",
    "json5",
    "jsonc",
    "jsonnet",
    "kconfig",
    "latex",
    "lua",
    "luadoc",
    "make",
    "markdown",
    "markdown_inline",
    "matlab",
    "mermaid",
    "meson",
    "ninja",
    "nix",
    "objdump",
    "ocaml",
    "ocaml_interface",
    "pascal",
    "passwd",
    "pem",
    "perl",
    "php",
    "phpdoc",
    "promql",
    "properties",
    "pug",
    "pymanifest",
    "python",
    "query",
    "rasi",
    "regex",
    "requirements",
    "ruby",
    "rust",
    "scheme",
    "scss",
    "sql",
    "ssh_config",
    "strace",
    "svelte",
    "toml",
    "tsx",
    "typescript",
    "v",
    "vala",
    "verilog",
    "vim",
    "vimdoc",
    "vue",
    "xml",
    "yaml",
    "zig",
  }
elseif vim.fn.has("win64") == 1 then
  config.ensure_installed = {
    "java",
    "kotlin",
    "javascript",
    "lua",
    "python",
  }
end

require("nvim-treesitter.configs").setup(config)

vim.g.skip_ts_context_commentstring_module = true
require("ts_context_commentstring").setup()
require("treesitter-context").setup({
  enable = true,
  mode = "topline",
})
-- require("kraftwerk28.plugins.treesitter_blockmark")
